### PR TITLE
Add dashboard authentication

### PR DESCRIPTION
**Pull request by jkilpatr**
This adds http auth to the Rita dashboard endpoints, before any value
is set no password is requested, once a new value is set it will be
used from there on out.

### CODE REVIEW

**Comment by jkilpatr** [comment]
setting the local password doesn't work and the sha digest doesn't seem to match sha3sum on the console (possible assci versus utf encoding issue?)

**Comment by jkilpatr** [comment]
the issue was not using fixed length sha3 encoding and such. Also upgraded to 512

**Comment by jkilpatr** [comment]
@asoltys  so we probably want to use a repo on the althea github, also your commit message for your unauthorized changed is really bad and should probably be expanded. Once we've got this setup to operate from the althea github and all that we should be good.

**Comment by asoltys** [comment]
Ok I forked the repo and also rebased on master a little more cleanly so this should be ready to merge now. Just waiting on Travis.

**Pull request merged**
